/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controller.PoblacionControl;
import controller.ed.lista.ListaEnlazada;
import java.util.Calendar;
import modelo.PoblacionDatos;
import vista.modeloTabla.ModeloTablaDatos;

/**
 *
 * @author Edison
 */
public class FrmAleatorios extends javax.swing.JDialog {

    private ModeloTablaDatos modelo = new ModeloTablaDatos();
    private PoblacionControl pc = new PoblacionControl();


    /**
     * Creates new form FrmAleatorios
     */
    public FrmAleatorios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //tblOrdenacion.setVisible(false);
        cargarTabla();

    }

    private void cargarTabla() {
        modelo.setLista(pc.getPc());
        tblPoblacion.setModel(modelo);
        tblPoblacion.updateUI();
        tblOrdenacion.setVisible(false);
    }

// Aqui llamamos el metodo QuickSortDes del Poblacion Controller
    private void quicksortDES() {
        //Tambien calculamos el tiempo de ejecucion
        long startTime = System.currentTimeMillis();
        modelo.setLista(pc.quicksortDes(pc.getPc()));
        long finalTime = System.currentTimeMillis() - startTime;
        jLabel2.setText("QuickSort Descendente :"+finalTime);
         tblOrdenacion.setVisible(true);
        tblOrdenacion.setModel(modelo);
        tblOrdenacion.updateUI();

    }

    private void quicksortAS() {
        long startTime = System.currentTimeMillis();
        modelo.setLista(pc.quicksortAs(pc.getPc()));
        long finalTime = System.currentTimeMillis() - startTime;
        jLabel2.setText("QuickSort Ascendente :"+finalTime);
        tblOrdenacion.setVisible(true);
        tblOrdenacion.setModel(modelo);
        tblOrdenacion.updateUI();

    }

    private void mergesortAS() {
        long startTime = System.currentTimeMillis();
        modelo.setLista(pc.mergeSortA(pc.getPc()));
        long finalTime = System.currentTimeMillis() - startTime;
        jLabel2.setText("MergeSort Ascendente :"+finalTime);
        tblOrdenacion.setModel(modelo);
        tblOrdenacion.updateUI();

    }

    private void mergesortDes() {
       long startTime = System.currentTimeMillis();
        modelo.setLista(pc.mergeSortDe(pc.getPc()));
        long finalTime = System.currentTimeMillis() - startTime;
        jLabel2.setText("MergeSort Descendente :"+finalTime);
        tblOrdenacion.setModel(modelo);
        tblOrdenacion.updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnQuickSortAs = new javax.swing.JButton();
        btnQuickSortDes = new javax.swing.JButton();
        btnMergeSortAs = new javax.swing.JButton();
        btnMergeSortDes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoblacion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrdenacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 158, 97));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "DATOS"));

        btnQuickSortAs.setBackground(new java.awt.Color(98, 98, 102));
        btnQuickSortAs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuickSortAs.setText("QuickSort As");
        btnQuickSortAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickSortAsActionPerformed(evt);
            }
        });

        btnQuickSortDes.setBackground(new java.awt.Color(98, 98, 102));
        btnQuickSortDes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuickSortDes.setText("QuickSort Des");
        btnQuickSortDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickSortDesActionPerformed(evt);
            }
        });

        btnMergeSortAs.setBackground(new java.awt.Color(98, 98, 102));
        btnMergeSortAs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMergeSortAs.setText("MergeSort As");
        btnMergeSortAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeSortAsActionPerformed(evt);
            }
        });

        btnMergeSortDes.setBackground(new java.awt.Color(98, 98, 102));
        btnMergeSortDes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMergeSortDes.setText("MergeSort Des");
        btnMergeSortDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeSortDesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnMergeSortAs)
                .addGap(26, 26, 26)
                .addComponent(btnMergeSortDes)
                .addGap(18, 18, 18)
                .addComponent(btnQuickSortAs)
                .addGap(31, 31, 31)
                .addComponent(btnQuickSortDes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuickSortAs)
                    .addComponent(btnQuickSortDes)
                    .addComponent(btnMergeSortAs)
                    .addComponent(btnMergeSortDes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblPoblacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPoblacion);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Tiempo de ejecucion: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("..................................");

        tblOrdenacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOrdenacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuickSortDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickSortDesActionPerformed
        // TODO add your handling code here:
        quicksortDES();
    }//GEN-LAST:event_btnQuickSortDesActionPerformed

    private void btnQuickSortAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickSortAsActionPerformed
        // TODO add your handling code here:
        quicksortAS();
    }//GEN-LAST:event_btnQuickSortAsActionPerformed

    private void btnMergeSortAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeSortAsActionPerformed
        // TODO add your handling code here:
        mergesortAS();
    }//GEN-LAST:event_btnMergeSortAsActionPerformed

    private void btnMergeSortDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeSortDesActionPerformed
        // TODO add your handling code here:
        mergesortDes();
    }//GEN-LAST:event_btnMergeSortDesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAleatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAleatorios dialog = new FrmAleatorios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMergeSortAs;
    private javax.swing.JButton btnMergeSortDes;
    private javax.swing.JButton btnQuickSortAs;
    private javax.swing.JButton btnQuickSortDes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrdenacion;
    private javax.swing.JTable tblPoblacion;
    // End of variables declaration//GEN-END:variables

}
